# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Notes on how to set ENV vars for multiple jobs. https://github.com/actions/starter-workflows/issues/68
env:
  APP_NAME: rnwolfapp2
  APP_LOCATION: __app__
  PYTHON_VERSION: "3.7"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('dev-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: List files to aid debugging
      run: ls -l
    - name: Install tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r dev-requirements.txt
    - run: mypy --config-file=mypy.ini __app__
    - run: black --check .

  deploy:

    needs: [lint]
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('dev-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 'Run pip'
      shell: bash
      run: |
        # If your function app project is not located in your repository's root
        # Please change your directory for pip in pushd
        pushd ${{ env.APP_LOCATION }}
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd
    - uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.APP_NAME }} 
        package: ${{ env.APP_LOCATION }}
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
